apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: sonarqube
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.containerPort }}
          name: web
        env:
          - name: SONAR_JDBC_URL
            valueFrom:
              secretKeyRef:
                name: sonarqube-secret
                key: SONAR_JDBC_URL
          - name: SONAR_JDBC_USERNAME
            valueFrom:
              secretKeyRef:
                name: sonarqube-secret
                key: SONAR_JDBC_USERNAME
          - name: SONAR_JDBC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sonarqube-secret
                key: SONAR_JDBC_PASSWORD
        volumeMounts:
        - name: sonarqube
          mountPath: /opt/sonarqube/logs
        - name: sonarqube
          mountPath: /opt/sonarqube/data
      volumes:
        - name: sonarqube
          persistentVolumeClaim:
            claimName: sonarqube