apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi