apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-secret
  namespace: sonarqube
data:
  SONAR_JDBC_URL: {{ .Values.jdbc.url | b64enc }}
  SONAR_JDBC_PASSWORD: {{ .Values.jdbc.password | b64enc }}
  SONAR_JDBC_USERNAME: {{ .Values.jdbc.username | b64enc }}